### ISSUE TITLE
Calling ${1}

### ISSUE THREAD

**Issue by aaronbwcollins** [brysontyrrell/EncryptedStrings#1]
In policy parameters isn't 1 - 3 reserved? Should calling ${4} be considerd the first parameter definable?

Thanks in advanced!

**Comment by brysontyrrell** [comment]
@aaronbwcollins for parameters that are being passed to the script, yes, but in this case we're talking about parameters to a function.

**Comment by aaronbwcollins** [comment]
When I run the scrip based on the usage $ sh EncryptedStrings_Bash.sh GenerateEncryptedString "string" Nothing is printed to standard out, am I missing something?

**Comment by brysontyrrell** [comment]
@aaronbwcollins GeneratEncryptedString() is a function within the script you can use in your own. You won't be able to call it from the command line the way you describe.

**Comment by aaronbwcollins** [comment]
@brysontyrrell Got it to work. Thanks.
